schedule:
  interval_minutes: 180
lockfile:
  base_dir: /home/egirg/shared/trading_prod
  trigger_name: channel_tracker_trigger.lock
  exit_name: channel_tracker_exit.lock
  lock_name: channel_tracker.lock
  check_seconds: 60
log_file: channel_sync
includes:
  - config/combined_config.yaml