database:
  mysql:
    user: trading_dev_user
    password: devStrongPass2025!
    host: localhost
    port: 3306
    database: Trading_dev
telegram:
  api_id: 27715324
  api_hash: 72f0a5168ab258f7b6cb169c78ff31d6
  phone: "+14698380038"
  session_path: sessions/my_telegram_client.session
processes:
  - name: channel_sync
    template: sync_template
templates:
  sync_template:
    enabled: true
    retry_count: 3
telegramHistoryRawUpdater:
  fetch:
    batch_size: 500
    sleep_seconds: 2
    log_file_name: telegram_fetch
    pause_seconds: 5
    days_limit: 90
    max_retries: 3
    base_dir: temp_messages
    lockfile:
      base_dir: locks
      name: telegram_fetch.lock